baseURL: "http://10.179.5.96:33000"
title: "My Hugo Blog"
theme: "PaperMod"

params:
  author: "Wyson Cheng"

  homeInfoParams:
    Title: Hi there
    Content: Welcome to my blog

  socialIcons:
    - name: "github"
      url: "https://github.com/ysonC"
