baseURL: "http://10.179.5.96:33000"
title: "My Super Juicy Blog"
theme: "PaperMod"

params:
  author: "Wyson Cheng"

  homeInfoParams:
    Title: Hi there
    Content: Welcome to my blog

  socialIcons:
    - name: "github"
      url: "https://github.com/ysonC"
  menu:
    main:
      - name: Home
        url: /
        weight: 5
      - name: "Blog"
        url: "/posts/"
        weight: 2
      - name: "Tags"
        url: "/tags/"
        weight: 3
      - name: "About"
        url: "/about/"
        weight: 4
      - name: "GitHub"
        url: "https://github.com/ysonC"
        weight: 5

  ShowBreadCrumbs: true
  ShowMenuItems: 5
