baseURL: "http://10.179.5.96:33000"
title: "My Super Juicy Blog"
theme: "PaperMod"

menu:
  main:
    - name: Archive
      url: archives
      weight: 5
    - name: Tags
      url: tags/
      weight: 10
    - name: Github
      url: https://github.com/ysonC

params:
  author: "Wyson Cheng Test1 2 3"

  homeInfoParams:
    Title: Hi there
    Content: Welcome to my blog

  socialIcons:
    - name: "github"
      url: "https://github.com/ysonC"

  ShowBreadCrumbs: true

