#!/bin/bash

echo "Start syncing and processing image links in Markdown files..."
if [ ! -f "sync_blogs.py" ]; then
    echo "Python script images.py not found."
    exit 1
fi

echo "Running python script to sync blogs..."
if ! python3 sync_blogs.py; then
    echo "Failed to process image links."
    exit 1
fi

echo "Building the Hugo site..."
if ! hugo; then
    echo "Hugo build failed."
    exit 1
fi

echo "Syncing file to nginx docker..."
rsync -avz --delete public/ /home/yson-server/docker-services/nginx/blog

echo "Staging changes for Git..."
if git diff --quiet && git diff --cached --quiet; then
    echo "No changes to stage."
else
    git add .
fi

commit_message="New Blog Post on $(date +'%Y-%m-%d %H:%M:%S')"
if git diff --cached --quiet; then
    echo "No changes to commit."
else
    echo "Committing changes..."
    git commit -m "$commit_message"
fi

echo "Deploying to GitHub Main..."
if ! git push origin main; then
    echo "Failed to push to main branch."
    exit 1
fi
