#!/bin/bash

echo "Start syncing from obsidian vault. . ."
rsync -av --delete "/srv/dev-disk-by-uuid-5d9f109b-e277-4117-973e-c7e67e8422ab/super_vault/yson/Obsidian Super Vault/posts/" "/home/yson-server/myblog/content/posts/"

echo "Processing image links in Markdown files..."
if [ ! -f "image_sync.py" ]; then
    echo "Python script images.py not found."
    exit 1
fi

echo "Starting up website. . ."
hugo server --bind 0.0.0.0 --baseURL http://10.179.5.96:1313/   
