#!/bin/bash

echo "Start syncing and processing image links in Markdown files..."
if [ ! -f "sync_blogs.py" ]; then
    echo "Python script images.py not found."
    exit 1
fi

echo "Running python script to sync blogs..."
if ! python3 sync_blogs.py; then
    echo "Failed to process image links."
    exit 1
fi

echo "Starting up website. . ."
hugo server --bind 0.0.0.0 --baseURL http://10.179.5.96:1313/   

