name: Hugo Build & Deploy

on:
  repository_dispatch:
    types: [build_hugo]  # This matches the event triggered from the Vault repo

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Hugo Repository
        uses: actions/checkout@v4
        
      - name: Install Hugo
        run: |
          echo "Installing Hugo..."
          sudo apt-get update && sudo apt-get install -y hugo
          
      - name: Checkout Private Vault Repo (Pull Blog Folder)
        uses: actions/checkout@v4
        with:
          repository: ysonC/super-obsidian-vault  # Change this to match your private vault repo
          token: ${{ secrets.VAULT_PAT }}  # Secret stored in Hugo repo
          path: vault

      - name: Copy Blog Content
        run: |
          echo "Copying updated blog posts from Vault repo..."
          rsync -av --delete vault/posts/ content/posts/

      - name: Build Hugo Site
        run: |
          echo "Building Hugo site..."
          hugo --minify

      - name: Commit & Push Changes
        run: |
          echo "Committing and pushing updated Hugo site..."
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Updated site from vault" || echo "No changes to commit"
          git push
