name: Hugo Build & Deploy

on:
  repository_dispatch:
    types: [build_hugo]  # Triggered from Vault repo
  push:
    paths:
      - "config.yml"

jobs:
  build_and_deploy:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout Hugo Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          path: hugo  # Checkout Hugo repo into "hugo" directory

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.142.0'
          extended: true  # Use Hugo Extended if needed

      - name: Checkout Private Vault Repo (Pull Blog Folder)
        uses: actions/checkout@v4
        with:
          repository: ysonC/super-obsidian-vault  # Change to your Vault repo
          fetch-depth: 0
          token: ${{ secrets.VAULT_PAT }}
          path: vault  # Checkout Vault repo into "vault" directory

      - name: Copy Blog Content into Hugo Repo
        run: |
          echo "Copying updated blog posts from Vault repo to Hugo repo..."
          python3 hugo/copy_images.py

      - name: Build Hugo Site
        run: |
          cd hugo  # Switch to Hugo repo directory
          echo "Updating submodules..."
          git submodule update --init --recursive
          echo "Building Hugo site..."
          hugo --minify # Now runs with themes and config
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Bump Version and Tag
        id: bump_version
        working-directory: hugo
        run: |
          # Initialize VERSION file if it doesn't exist
          if [ ! -f VERSION ]; then
            echo "0.0.0" > VERSION
          fi
          current_version=$(cat VERSION)
          echo "Current version: $current_version"
          # Split the version into major, minor, and patch numbers
          IFS='.' read -r major minor patch <<< "$current_version"
          # Increment the patch number (adjust logic as needed for minor/major bumps)
          new_patch=$((patch + 1))
          new_version="${major}.${minor}.${new_patch}"
          echo "New version: $new_version"
          # Update the VERSION file with the new version
          echo "$new_version" > VERSION
          # Set the new version as an output variable for subsequent steps
          echo "::set-output name=new_version::$new_version"
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./hugo   # Ensure it builds from the Hugo directory
          file: ./hugo/Dockerfile  # Ensure it uses the correct Dockerfile
          push: true
          tags: wyson002/my-hugo-blog:v${{ steps.bump_version.outputs.new_version }},wyson002/my-hugo-blog:latest
          platforms: linux/arm64
      
      - name: Commit & Push Changes
        run: |
          echo "Committing and pushing updated Hugo site..."
          cd hugo  # Ensure we're in the Hugo repo
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Updated site from Vault" || echo "No changes to commit"
          git push
