name: Hugo Build & Deploy

on:
  repository_dispatch:
    types: [build_hugo]  # Triggered from Vault repo
  push:
    paths:
      - "config.yml"

jobs:
  build_and_deploy:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout Hugo Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          path: hugo  # Checkout Hugo repo into "hugo" directory

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.142.0'
          extended: true  # Use Hugo Extended if needed

      - name: Checkout Private Vault Repo (Pull Blog Folder)
        uses: actions/checkout@v4
        with:
          repository: ysonC/super-obsidian-vault  # Change to your Vault repo
          fetch-depth: 0
          token: ${{ secrets.VAULT_PAT }}
          path: vault  # Checkout Vault repo into "vault" directory

      - name: Copy Blog Content into Hugo Repo
        run: |
          echo "Copying updated blog posts from Vault repo to Hugo repo..."
          python3 hugo/copy_images.py

      - name: Build Hugo Site
        run: |
          cd hugo  # Switch to Hugo repo directory
          echo "Updating submodules..."
          git submodule update --init --recursive
          echo "Building Hugo site..."
          hugo --minify # Now runs with themes and config
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and Push docker image
        run: |
          echo "Building docker image..."
          cd hugo
          echo "Building docker image..."
          docker build --platform linux/arm64 -t wyson002/my-hugo-blog .
          echo "Pushing docker image..."
          docker push wyson002/my-hugo-blog
          echo "Docker image built."
          
      - name: Copy Web Content to docker
        run: |
          echo "Rsyncing to docker folder..."
          rsync -avz --delete hugo/public/ /home/yson-server/docker-services/nginx/blog/public
          echo "Rsync complete."
          
      - name: Commit & Push Changes
        run: |
          echo "Committing and pushing updated Hugo site..."
          cd hugo  # Ensure we're in the Hugo repo
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Updated site from Vault" || echo "No changes to commit"
          git push
